name: script_runner
description: Run all your project-related scripts in a portable, simple config.
version: 0.1.2
homepage: https://casraf.blog/dart-script-runner/
repository: https://github.com/chenasraf/dart_script_runner
license: MIT
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  file: ^6.1.2
  path: ^1.8.2
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

script_runner:
  shell: /bin/zsh
  scripts:
    - name: echo1
      cmd: echo "Hello World"
      description: test script foobar
    - name: echo2
      cmd: echo
      args:
        - 'Hello World'
      description: test script foobar
    - name: activate-local
      cmd: dart pub global activate --source path ~/Dev/script_runner
    - name: combined
      cmd: echo 'test' && echo1 && echo2
    - short: echo 'this is a short script'
    - auto-fix: dart fix --apply

executables:
  dartsc: script_runner
