name: script_runner
description: Run all your project-related scripts in a portable, simple config.
version: 0.6.0
homepage: https://casraf.dev/
repository: https://github.com/chenasraf/dart_script_runner
license: MIT
environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  file: ^7.0.0
  path: '>=1.8.0 <2.0.0'
  unaconfig: ^0.1.3
  # unaconfig:
  #   path: ../unaconfig

dev_dependencies:
  lints:
  test:
  btool:

script_runner:
  # line_length: 100
  scripts:
    # Real
    - auto-fix: dart fix --apply
    - publish: dart format .; dart pub publish; format
    - publish:dry: dart pub publish --dry-run
    - doc: dart doc
    - name: version
      cmd: dart run btool get packageVersion
      display_cmd: false
    - name: 'version:set'
      cmd: dart run btool set packageVersion
      display_cmd: false
    - format: dart format --line-length 120 .

    # Examples
    - name: echo1
      cmd: echo "Hello World" $SHELL
      description: Interdum a scelerisque arcu felis taciti ligula pellentesque curabitur, suspendisse adipiscing quisque sed luctus elementum in imperdiet id, praesent enim sem justo sapien diam nec. Quisque erat risus sagittis penatibus per, vehicula sociosqu cubilia convallis, sollicitudin scelerisque cras aptent. Natoque ornare dictumst netus litora mollis suspendisse cubilia proin morbi primis consequat eu massa, cursus non urna ridiculus dolor duis tempus ut nam velit lacus viverra. A interdum senectus eu mus leo aptent facilisi augue tristique ante purus condimentum pulvinar porta viverra morbi, et tellus gravida porttitor non euismod suscipit neque egestas praesent arcu luctus pharetra fusce. Luctus mauris a venenatis tempus cras ante efficitur massa ultricies mollis lacus, volutpat nisi lacinia himenaeos facilisi in aliquet sodales purus integer vitae quisque, libero torquent enim mattis placerat tortor mi dignissim viverra sem.
    - name: echo2
      cmd: echo
      args:
        - 'Hello World'
      description: test script foobar
      display_cmd: false
    - name: activate-local
      cmd: dart pub global activate --source path ./
    - name: activate-global
      cmd: dart pub global activate script_runner
    - name: combined
      cmd: echo 'test' && echo1 && echo2
    - short: echo 'this is a short script'
    - name: error
      cmd: |-
        _fn() {
          return 1
        }
        _fn
      description: imitate error

executables:
  scr: script_runner
