name: script_runner
description: Run all your project-related scripts in a portable, simple config.
version: 0.1.7
homepage: https://casraf.dev/
repository: https://github.com/chenasraf/dart_script_runner
license: MIT
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  file: ^6.1.2
  path: ^1.8.2
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

script_runner:
  # line_length: 100
  scripts:
    # Real
    - auto-fix: dart fix --apply
    - publish: dart pub publish
    - doc: dart doc

    # Examples
    - name: echo1
      cmd: echo "Hello World" $SHELL
      description: Interdum a scelerisque arcu felis taciti ligula pellentesque curabitur, suspendisse adipiscing quisque sed luctus elementum in imperdiet id, praesent enim sem justo sapien diam nec. Quisque erat risus sagittis penatibus per, vehicula sociosqu cubilia convallis, sollicitudin scelerisque cras aptent. Natoque ornare dictumst netus litora mollis suspendisse cubilia proin morbi primis consequat eu massa, cursus non urna ridiculus dolor duis tempus ut nam velit lacus viverra. A interdum senectus eu mus leo aptent facilisi augue tristique ante purus condimentum pulvinar porta viverra morbi, et tellus gravida porttitor non euismod suscipit neque egestas praesent arcu luctus pharetra fusce. Luctus mauris a venenatis tempus cras ante efficitur massa ultricies mollis lacus, volutpat nisi lacinia himenaeos facilisi in aliquet sodales purus integer vitae quisque, libero torquent enim mattis placerat tortor mi dignissim viverra sem.
    - name: echo2
      cmd: echo
      args:
        - 'Hello World'
      description: test script foobar
    - name: activate-local
      cmd: dart pub global activate --source path ./
    - name: combined
      cmd: echo 'test' && echo1 && echo2
    - short: echo 'this is a short script'

executables:
  scr: script_runner
